---
- name: Configure EC2 instance
  hosts: local
  connection: local
  gather_facts: false

  vars_files:
    - vars/vars.yml

  tasks:
    - name: Create EC2 instance
      import_tasks: tasks/ec2_create.yml

- name: Provision EC2 instance
  hosts: web
  remote_user: ubuntu
  become: true
  gather_facts: true

  vars_files:
    - vars/vars.yml

  tasks:
    - import_tasks: tasks/update.yml
    - import_tasks: tasks/user.yml
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/configs.yml
    - import_tasks: tasks/motd.yml
    - import_tasks: tasks/passenger_apache.yml
    - import_tasks: tasks/app_prep.yml
    - import_tasks: tasks/prometheus.yml
    - import_tasks: tasks/harden.yml
    - import_tasks: tasks/restart.yml
      tags: restart
